### PR TITLE
Manage controller - redisplay views instead of exceptions

### LINKED ISSUE #476: [Prod] Error while changing username to one which already exist
1. Login to the prod env
2. Try to change Username for one, which already exist
3. Click zapisz

image

### PR DESCRIPTION
**Pull request by Mejtika**
## Description

I've changed the logic in manage controller to redisplay view in case of errors, instead of throwing an exception.

## Where should the reviewer start?

Run the app and try to change to the existing email/username.

## Motivation and context

Close #476 

## Screenshots (if appropriate)
image
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

File: src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/ManageController.cs [hunk 1]
```diff
@@ -176,11 +180,6 @@ await this._emailNotificationService
                 return await this.SendVerificationEmail(model).ConfigureAwait(false);
             }
 
-            if (shouldSendVerificationEmail)
```
Comment (WTobor) [inline src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/ManageController.cs:179]: why have you removed it?

File: src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/ManageController.cs [hunk 2]
```diff
@@ -96,13 +96,16 @@ public async Task<IActionResult> Index(IndexViewModel model)
                 throw new ArgumentNullException(nameof(model));
             }
 
+            model.IsEmailConfirmed = user.EmailConfirmed;
```
Comment (WTobor) [inline src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/ManageController.cs:99]: hmmm why?

**Review by WTobor — APPROVED** [review]
