### PR TITLE
email confirmation redirect and change api action from get to post

### LINKED ISSUE #348: API review - email confirmation
**Steps to reproduce**

Using the dev site.

1. Go to address, for example: https://dev.devadventcalendar.pl/Account/ConfirmEmail?userId=1&code=1234564564564564df6sadasdsa
2. Observe HTTP response.

**Current behavior**

A HTTP 500 error will be returned with stacktrace if code/token is not valid. 
Also, the GET method is being used to update state.

**Expected behavior**

Client should be redirected to the Error view.
Would be better to use POST/PUT instead of GET.

### PR DESCRIPTION
**Pull request by szrtGreg**
## Description
API review. Change method request from GET to POST  and redirect user to error page when confirmation link is not valid

## Where should the reviewer start?
AccountController

## Motivation and context
closes #348 

## How has this been tested?
Go to address, for example: https://dev.devadventcalendar.pl/Account/ConfirmEmail?userId=1&code=1234564564564564df6sadasdsa
Should return ErrorPage

Tests are completed sucessfully
Adding new users/confirm emails working correctly.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by szrtGreg** [comment]
Becouse typing https://dev.devadventcalendar.pl/Account/ConfirmEmail?userId=1&code=1234564564564564df6sadasdsa in URL is a default GET request. I devided method ConfirmEmail into Get and Post portion.
1) GET portion does redirect to error pages
2) POST change application state.

**Comment by WTobor** [comment]
@szrtGreg the issue description is simple - `ConfirmEmail` method should be POST, not GET (because it is changing the state). Please do this that way.

In `Startup` we have `app.UseDeveloperExceptionPage();` so you will have a different result from the PROD or DEV environment

Please remove `ConfrimEmailCompleted` method - there is not point to create it here

We will discuss GET and POST requests during our tomorrow sync call (please be prepared :))

View `Error`needs `ErrorViewModel`

**Comment by szrtGreg** [comment]
Nah.. I thought it was a brilliant idea :) I revert changes. Although I found interesting bug on both PROD and DEV environment. Lets focus od production site.

When you go
https://devadventcalendar.pl/Account/ConfirmEmail?userId=1&code=
Site is working correctly -redirect to main index page

When you go
https://devadventcalendar.pl/Account/ConfirmEmail?userId=1&code=x
(adding parametr to code variable)
Site is blank and not redirect to error page or main page

**Comment by WTobor** [comment]
You have logic:
```
if (userId == null || code == null)
{
       return this.RedirectToAction(nameof(HomeController.Index), "Home");
}
```
that's why you are redirected to main page

**Comment by szrtGreg** [comment]
Agree - code indicate this behaviour. My question is: Does it work as we want?

File: src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs [hunk 1]
```diff
@@ -262,23 +262,24 @@ public async Task<IActionResult> ExternalLoginConfirmation(ExternalLoginViewMode
...
             }
 
             if (user.EmailConfirmed)
             {
                 return this.View("EmailAlreadyConfirmed");
             }
 
-            return await this.ConfrimEmailCompleted(userId, code);
+            var result = await this._accountService.ConfirmEmailAsync(user, code).ConfigureAwait(false);
+            return this.View(result.Succeeded ? "ConfirmEmail" : "Error");
```
Comment (WTobor) [inline src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs]:
```
if (!result.Succeeded)
{
   throw new InvalidOperationException();
}
return this.View();
```

File: src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs [hunk 2]
```diff
@@ -279,6 +279,11 @@ public async Task<IActionResult> ConfirmEmail(string userId, string code)
             }
 
             var result = await this._accountService.ConfirmEmailAsync(user, code).ConfigureAwait(false);
+            if (!result.Succeeded)
+            {
+                throw new InvalidOperationException();
+            }
+
             return this.View(result.Succeeded ? "ConfirmEmail" : "Error");
```
Comment (WTobor) [inline src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs:287]: you just checked `result.Succeeded` in line 282. So here all you need to do is returning View. So just adding the code, that I wrote before :)

File: src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs (hunk 1 above)
Comment (szrtGreg) [reply src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs]: done

File: src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs [hunk 3]
```diff
@@ -284,7 +284,7 @@ public async Task<IActionResult> ConfirmEmail(string userId, string code)
                 throw new InvalidOperationException();
```
Comment (WTobor) [inline src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs:284]: please add a descriptive error message in resource

File: src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs [hunk 4]
```diff
@@ -270,7 +272,7 @@ public async Task<IActionResult> ConfirmEmail(string userId, string code)
             var user = await this._accountService.FindByIdAsync(userId).ConfigureAwait(false);
             if (user == null)
             {
-                throw new ArgumentException($"Nie można załadować użytkownika z identyfikatorem '{userId}'.");
+                throw new ArgumentException(@ErrorDuringEmailConfiguration,  @userId);
```
Comment (WTobor) [inline src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs:275]: have you checked that? It will not show a proper message - you should use `String.Format`

Comment (szrtGreg) [reply src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs:275]: To be honest. As far I understand what I am doing it looks correct:
obraz

Comment (WTobor) [reply src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs:275]: it should be `Wystąpił nieoczekiwany błąd podczas konfigurowania wiadomości e-mail dla użytkownika z identyfikatorem '1'`

Comment (szrtGreg) [reply src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs]: done
